media: media
  content:
    - name: posts
      label: Blog Posts
      type: collection
      path: '_posts'
      view:
        fields: [title, published, date]
      fields:
        - name: published
          label: Published
          type: boolean
          default: true
        - name: date
          label: Date
          type: date
        - name: title
          label: Title
          type: string
        - name: body
          label: Body
          type: rich-text
        - name: cmalt
      label: CMALT Files
      type: collection
      path: '_cmalt'
      view:
        fields: [title]
      fields:
        - name: title
          label: Title
          type: string
        - name: body
          label: Body
          type: rich-text
    - name: config
      label: Site Configuration
      path: '_config.yml'
      type: file
      fields:
        - name: title
          label: Site Title
          type: string
        - name: description
          label: Site Description
          type: string
        - name: url
          label: Site URL
          type: string
          pattern: ^(https?:\/\/)?(www\.)?[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}(\/[^\s]*)?$

